questions[
"Would you rather Eat a jar of peanut butter or Drink a jar of maple syrup?",
"Would you rather live one life that lasts 1,000 years or live 10 lives that last 100 years each?",
"Would you rather use eye drops made of vinegar or toilet paper made from sandpaper?",
"Would you rather be without elbows or be without knees?",
"Would you rather experience a sharp pain in your side each time someone says your name or have a bell sound each time you are aroused?",
"Would you rather have a large 10 inch long belly button that swayed to music or have accordions for legs?",
"Would you rather have to sneeze but not be able to or have something stuck in your eye for an entire year?",
"Would you rather have a dragon or be a dragon?",
"Would you rather have hair nowhere on your body or be very hairy all over and not be able to shave?",
"Would you rather never be able to speak again or always have to say everything that is on your mind?",
"Would you rather be able to read or be able to read minds (but be illiterate)?",
"Would you rather be able to speak fluently every language in the world or be the best in the world at something of your choosing?",
"Would you rather be in prison for five years in solitary confinement or not ever go to prison and not ever become rich?",
"Would you rather wear a snow suit in the desert or be naked in Antarctica?",
"Would you rather change the past or be able to see into the future?",
"Would you rather have cookies or have French fries?",
"Would you rather be good at sports or get good grades?",
"Would you rather help clean up after dinner or help set the table before dinner?",
"Would you rather get up early or stay up late?",
"Would you rather be super fast or super strong?",
"Would you rather be invisible or have the ability to fly?",
"Would you rather be the smartest kid in school or the most popular kid in school?",
"Would you rather eat your boogers or lick your shoe?",
"Would you rather have bad breath or smelly feet?",
"Would you rather be a police officer or be a firefighter?"
]
