children-questions[
"Would you rather eat chips or candy?",
"Would you rather have fries or cookies?",
"Would you rather eat pizza or hot dogs?",
"Would you rather be a firefighter or a police officer?",
"Would you rather be a doctor or a garbage man?",
"Would you rather be a chef or a waiter/waitress?",
"Would you rather be a teacher or a janitor?",
"Would you rather have smelly feet or bad breath?",
"Would you rather never have to shower again or never have to brush your teeth again?",
"Would you rather eat a live bug or a dead worm?",
"Would you rather lick your shoe or eat your boogers?",
"Would you rather get good grades or be a good athlete?",
"Would you rather be the most popular kid in school or the smartest kid in school?",
"Would you rather only be able to whisper or only be able to shout?",
"Would you rather be super strong or super fast?",
"Would you rather be really tall or really short?",
"Would you rather have the ability to fly or to be invisible?",
"Would you rather always have to say everything that you are thinking or never speak again?",
]

adult-questions[
"Would you rather get explosive diarrhea every time you meet your boss or every time you meet your SO’s parents?",
"Would you rather have a head the size of a tennis ball or the size of a watermelon?",
"Would you rather have the best house in a bad neighborhood or the worst house in a fancy neighborhood?",
"Would you rather freeze to death or burn to death?",
"Would you rather have no arms or no legs?",
"Would you rather have no fingers or no eyes?",
"You can only hear one song for the rest of your life. Bohemian Rhapsody or Ring of Fire?",
"Would you rather have a time machine that only goes back in time or a time machine that only goes forward in time?",
"Would you rather have unlimited love or unlimited money?",
"Would you rather have unlimited respect or unlimited power?",
"Would you rather be an ugly genius or a hot moron?",
"Would you rather never have internet access again or never be able to take an airplane again?",
"Would you rather smell terrible (but you can’t smell it) or your partner smell terrible and you have to smell it?"
]

funny-questions[

]

hard-questions[
"Use sandpaper for toilet paper OR vinegar for eye drops?",
"poop bricks OR puke slugs?",
"Have no knees OR no elbows?",
"Eat a bowl of poop once OR have explosive diarrhoea for the rest of your life?",
"Have something in your eye OR need to sneeze but never be able to, for a year?",
"Be a dragon OR have a dragon?",
"Be really hairy all over your body and not be able to shave OR not have one hair anywhere?",
"Be rich and ugly OR poor and good looking?",
"Always have to say everything on your mind OR never speak again?",
"Be 3 feet shorter OR 3 feet taller?",
"Have one wish granted now OR 3 wishes granted in ten years?",
"Lick a smelly man's armpit OR chew on his rotten toe nail?",
"Be buried alive OR stranded at sea?",
"See into the future OR change the past?",
"Spend five years in solitary confinement in prison and become rich OR never go to prison but never become rich?",
"Always have to tell the truth OR always lie?",
"Live in the Harry Potter universe OR the Pokémon universe?",
"Be naked in Antarctica OR wear a snow suit in the desert?",
"Spend 5 years in prison for something you didn't do OR ten years for something you did?",
"Always be slightly over-dressed OR always be slightly under-dressed?",
"Have a saw-off shotgun OR a flame-thrower, in a zombie apocalypse?"
]
